# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-09-06 15:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200905_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='dt',
            field=models.DateField(default=datetime.date(2020, 9, 6)),
        ),
    ]
