# Generated by Django 3.1.1 on 2020-09-08 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200906_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='dt',
            field=models.DateField(default=datetime.date(2020, 9, 8)),
        ),
    ]
