# Generated by Django 3.1.1 on 2020-09-09 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200908_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='dt',
            field=models.DateField(default=datetime.date(2020, 9, 9)),
        ),
    ]
